## Assignment 4

In [3]:
import pandas as pd
from helpers import load_and_preview

nhanes = pd.read_csv("../../../examples/nhanes-equity/data/nhanes_equity_v6.csv")

py_summary = (
    nhanes
    .dropna(subset=["BMI", "IncomeGroup", "Gender"])
    .groupby(["IncomeGroup", "Gender"], as_index=False)
    .agg(
        n=("BMI", "size"),
        mean_bmi=("BMI", "mean"),
        sd_bmi=("BMI", "std")
    )
    .sort_values(["IncomeGroup", "Gender"])
)

py_summary["mean_bmi"] = py_summary["mean_bmi"].round(1)
py_summary["sd_bmi"] = py_summary["sd_bmi"].round(2)

py_summary

/tmp/ipykernel_59967/1049577408.py:4: DtypeWarning: Columns (11: Marital, 15: MaritalClean) have mixed types. Specify dtype option on import or set low_memory=False.
  nhanes = pd.read_csv("../../../examples/nhanes-equity/data/nhanes_equity_v6.csv")

          IncomeGroup  Gender      n  mean_bmi  sd_bmi
0  High Income (>3.5)  Female  11743      25.7    7.51
1  High Income (>3.5)    Male  12095      26.1    6.81
2   Low Income (<1.3)  Female  16548      25.9    8.65
3   Low Income (<1.3)    Male  14847      24.0    7.17
4       Middle Income  Female  16432      26.4    8.20
5       Middle Income    Male  15982      25.5    7.22

## R and Python Parity Audit

In [4]:
len(nhanes)

105626

In [5]:
nhanes.columns.tolist()

['Cycle',
 'BMI',
 'Weight',
 'Height',
 'Waist',
 'WeightMEC',
 'Strata',
 'PSU',
 'Gender',
 'Race',
 'Education',
 'Marital',
 'Age',
 'PIR',
 'EducationClean',
 'MaritalClean',
 'IncomeGroup',
 'WHtR']

In [6]:
len(nhanes.dropna(subset=["BMI", "IncomeGroup", "Gender"]))

87647

In [7]:
len(py_summary)

6

In [8]:
py_summary[["mean_bmi", "sd_bmi"]]

   mean_bmi  sd_bmi
0      25.7    7.51
1      26.1    6.81
2      25.9    8.65
3      24.0    7.17
4      26.4    8.20
5      25.5    7.22

R and Python parity audit concluded to show that there is no difference between R and Python.

## Using Python Script

In [9]:
preview = load_and_preview("../../../examples/nhanes-equity/data/nhanes_equity_v6.csv")
preview

Loaded 105626 rows and 18 columns

/workspaces/HDSx_workspace/assignments/assignment04-polyglot/submission/helpers.py:11: DtypeWarning: Columns (11: Marital, 15: MaritalClean) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(csv_path)

,Cycle,BMI,Weight,Height,Waist,WeightMEC,Strata,PSU,Gender,Race,Education,Marital,Age,PIR,EducationClean,MaritalClean,IncomeGroup,WHtR
0,1999-2000,14.90,12.5,91.6,45.7,10982.898896,5,1,Female,Non-Hispanic Black,NaN,NaN,2,0.86,NaN,NaN,Low Income (<1.3),0.498908
1,1999-2000,24.90,75.4,174.0,98.0,28325.384898,1,3,Male,Non-Hispanic White,College Grad,NaN,77,5.00,College Grad,NaN,High Income (>3.5),0.563218
2,1999-2000,17.63,32.9,136.6,64.7,46192.256945,7,2,Female,Non-Hispanic White,NaN,NaN,10,1.47,NaN,NaN,Middle Income,0.473646
3,1999-2000,NaN,13.3,NaN,NaN,10251.260020,2,1,Male,Non-Hispanic Black,NaN,NaN,1,0.57,NaN,NaN,Low Income (<1.3),NaN
4,1999-2000,29.10,92.5,178.3,99.9,99445.065735,8,2,Male,Non-Hispanic White,College Grad,Married/Partner,49,5.00,College Grad,Married/Partner,High Income (>3.5),0.560292

In [11]:
from helpers import summarise_mean_sd
py_function_summary = summarise_mean_sd(nhanes, "BMI", "IncomeGroup", "Gender")
py_function_summary

          IncomeGroup  Gender      n  mean_value  sd_value
0  High Income (>3.5)  Female  11743       25.74      7.51
1  High Income (>3.5)    Male  12095       26.11      6.81
2   Low Income (<1.3)  Female  16548       25.95      8.65
3   Low Income (<1.3)    Male  14847       24.05      7.17
4       Middle Income  Female  16432       26.39      8.20
5       Middle Income    Male  15982       25.52      7.22